### ISSUE TITLE
Discovery error when loading Solana

### ISSUE THREAD

**Issue by whenwhale** [trezor/trezor-suite#11021]
Console log:
```
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: failed to get recent blockhash: TypeError: fetch failed
    at l.onMessage (/tmp/.mount_TrezorfpNRQn/resources/app.asar/dist/app.js:1:113891)
    at t.CONTEXT.post (/tmp/.mount_TrezorfpNRQn/resources/app.asar/dist/workers/blockbook-worker.js:1:11137)
    at g.errorResponse (/tmp/.mount_TrezorfpNRQn/resources/app.asar/dist/workers/blockbook-worker.js:1:12964)
    at g.<anonymous> (/tmp/.mount_TrezorfpNRQn/resources/app.asar/dist/workers/solana-worker.js:1:221394)
    at Generator.throw (<anonymous>)
    at a (/tmp/.mount_TrezorfpNRQn/resources/app.asar/dist/app.js:1:1568279)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Running the Trezor-Suite-24.1.2-linux-x86_64.AppImage

**Comment by MiroslavProchazka** [comment]
Hello @whenwhale, can you please describe steps how to reproduce the issue? 
Thanks!

**Comment by MiroslavProchazka** [comment]
Closing this until we will gather more info.
