### ISSUE TITLE
Coinmarket - unknown address validator for known networks

### ISSUE THREAD

**Issue by FreeWall** [trezor/trezor-suite#14249]
## Description

```
Error: Missing validator for currency: stellar--USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN
    at Object.validate (index.js:14:15)
    at validate (CoinmarketVerify.tsx:104:31)
    at validateField (index.esm.mjs:949:34)
    at onChange (index.esm.mjs:2014:32)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
```

## How to reproduce
1. Go to Trade > Exchange
2. Select BTC to USDC (stellar)
3. Select `Exchange` button
4. Enter valid address in `Receive address` (`GC7OHFPWPSWXL4HMN6TXAG54MTZSMJIASWHO6KVRQNHNCXEAHWDSGGC3`)

## Screenshots
![image](https://github.com/user-attachments/assets/79164900-a943-481e-81b8-84799ac5ee75)

**Comment by mroz22** [comment]
it looks like that `stellar--USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN` 
is used as a currency input into @trezor/address-validator lib

**Comment by bosomt** [comment]
i have new error when checking it @FreeWall 
`Error: pair_is_inactive`
Is that ok ? reopen ? ne issue ?


<img width="610" alt="Screenshot 2024-09-12 at 9 55 40" src="https://github.com/user-attachments/assets/446e8eee-af1a-4615-a6e4-a40f65edfedd">

**Info:**
 - Suite version: desktop 24.9.1 (d8848035b1badf8ef15fb0cecb6113bfc87326a9)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.9.1 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.2 regular (revision 37006592dbc3f2d817def0c75ed6a62513895ec5)
 - Transport: BridgeTransport 3.0.0

**Comment by bosomt** [comment]
**QA OK**

approved, created follow up issue
