### ISSUE TITLE
Autoupdate failing on NixOS

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2962]
Part of #2916. Throws `Error: Error: APPIMAGE env is not defined` during an update.

```
Trezor-Suite-20.10.1-linux.AppImage installed in /home/tsusanka//.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a
Checking for update
Found version 20.11.2 (url: Trezor-Suite-20.11.2-linux.AppImage)
Downloading update from Trezor-Suite-20.11.2-linux.AppImage
updater cache dir: /home/tsusanka/.cache/@trezorsuite-desktop-updater
Error: Error: APPIMAGE env is not defined
    at newError (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:212:17)
    at Object.task (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:108:52)
    at AppImageUpdater.executeDownload (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:756:25)
(node:5475) UnhandledPromiseRejectionWarning: Error: APPIMAGE env is not defined
    at newError (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:212:17)
    at Object.task (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/out/AppImageUpdater.js:108:52)
    at AppImageUpdater.executeDownload (/home/tsusanka/.cache/appimage-run/ed08ffd7c4d64cbd0729d34476963cdf37d68961142120f0ea52737b2b7ff43a/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:756:25)
(node:5475) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5475) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by prusnak** [comment]
This is most probably an issue with the `appimage-run` tool from NixOS which does not define APPIMAGE env variable. Oddly enough I was able to find this issue on other Linux-based OS as well - https://stackoverflow.com/questions/52442650/electron-builder-linux-updates-appimage-env-is-not-defined

The error comes from https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppImageUpdater.ts where it tries to erase the old AppImage file and replace it with the new contents! Honestly I dislike this and we could probably workaround this, but I am not sure what else will it break.

**Comment by keraf** [comment]
I think the easiest fix for that one is to define APPIMAGE on Linux if it doesn't exist. I guess it's based on where the application is running from?

**Comment by prusnak** [comment]
We won't be triggering auto-update on NixOS for reasons mentioned in https://github.com/trezor/trezor-suite/pull/3113#issuecomment-763788498
