### ISSUE TITLE
Dependencies(suite-desktop): update node-fetch to v3

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5564]
**Info**
https://github.com/trezor/trezor-suite/pull/4757#issuecomment-1018475180

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/trezor-suite/packages/suite-desktop/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /Users//trezor-suite/packages/suite-desktop/node_modules/node-fetch/src/index.js from /Users/trezor-suite/packages/suite-desktop/dist/app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": 
"module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/trezor-suite/packages/suite-desktop/node_modules/node-fetch/package.json.

    at new NodeError (node:internal/errors:370:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1128:13)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at scripts/build-inject.js (/Users/trezor-suite/packages/suite-desktop/dist/app.js:62:36)
    at __init (/Users/trezor-suite/packages/suite-desktop/dist/app.js:26:50)
    at Object.<anonymous> (/Users/trezor-suite/packages/suite-desktop/dist/app.js:6251:1)
    ```

**Comment by tomasklim** [comment]
https://github.com/trezor/trezor-suite/pull/5893

**Comment by tomasklim** [comment]
Will be done together with node18 update
