### ISSUE TITLE
jest: memory-leak, listeners, transport, usb

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#9236]
when running 
```
yarn workspace @trezor/suite test:unit
```
using test command as follows
```
"test:unit": "jest --version && node --trace-warnings node_modules/.bin/jest --no-cache",
```
we can see 

```
(node:152375) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 newListener listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at EventEmitter.addListener (node:events:605:10)
    at Object.<anonymous> (/Workspace/suite/node_modules/usb/tsc/usb/index.ts:142:5)
    at Runtime._execModule (/Workspace/suite/packages/suite/node_modules/jest-runtime/build/index.js:1429:24)
```

this happens because of nature of jest and event listener in usb lib being registered at import time here https://github.com/node-usb/node-usb/blob/master/tsc/usb/index.ts#L142

it should not imho be problem of production, only tests. 

work around on our side would be to import this lib dynamically in transport, probably in something like Transport.init method.

**Comment by szymonlesisz** [comment]
we can patch `suite/node_modules/usb/dist/usb/index.js` file with:
```
if (usb.listenerCount('newListener') === 0) {
    usb.on('newListener', function (event) {
        if (event !== 'attach' && event !== 'detach') {
            return;
        }
        var listenerCount = usb.listenerCount('attach') + usb.listenerCount('detach');
        if (listenerCount === 0) {
            startHotplug();
        }
    });
}

if (usb.listenerCount('removeListener') === 0) {
    usb.on('removeListener', function (event) {
        if (event !== 'attach' && event !== 'detach') {
            return;
        }
        var listenerCount = usb.listenerCount('attach') + usb.listenerCount('detach');
        if (listenerCount === 0) {
            stopHotplug();
        }
    });
}
```

then prepare some small testing repo as a proof for `nodeusb` lib that this issue exists  in case of dynamic/isolated imports (like jest)

and fix it in the [upstream](https://github.com/node-usb/node-usb/blob/master/tsc/usb/index.ts#L142C1-L142C1)

**Comment by matejkriz** [comment]
if it's not a real problem, just warning, you can relax it by setting higher limit: `usb.setMaxListeners(reasonableNumber)`

**Comment by szymonlesisz** [comment]
well, we are not 100% sure if it is real (production) problem or not. 
For suite-desktop it's not, i've tested it by putting some console logs into this file and hitting ctrl+R, but since connect -> transport packages are public and used by 3rd parties we cant tell how they are using them (maybe connect is dynamically imported somewhere?)

btw by setting MaxListeners you only silence the warning but the issue is deeper, multiple registered listeners will trigger multiple events instead of one -  like for example "device disconnected" more than once
